list = ['beta',786,2.23,'lambda',7123.2]
print("List: ",list)
print("1st element: ",list[0])
print("2nd to 4th element: ", list[1:4])
print("Elements from 3rd posn: ", list[2:])
print("List * 2: ", list*2)
print("Concat: ", list + ['party'])
list.append('john')
print("List append: ", list)
del list[2]
print("Deleted 3rd element: ",list)
print("Length of list: ",len(list))
print("Count of 'john' in list: ", list.count('john'))
print("Last element of list popped: ", list.pop())
list.insert(3,'party')
print("Insert 'party' at index 3: ", list)
list.remove('party')
print("Remove 'party':", list)
list.reverse()
print("Reversed list: ",list)
